/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as AppLayoutRouteImport } from './routes/app/_layout'
import { Route as AppLayoutIndexRouteImport } from './routes/app/_layout/index'
import { Route as AppLayoutSessionsRouteImport } from './routes/app/_layout/sessions'
import { Route as AppLayoutSessionsIdRouteImport } from './routes/app/_layout/sessions_.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/app/_layout',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutIndexRoute = AppLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutSessionsRoute = AppLayoutSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutSessionsIdRoute = AppLayoutSessionsIdRouteImport.update({
  id: '/sessions_/$id',
  path: '/sessions/$id',
  getParentRoute: () => AppLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app': typeof AppLayoutRouteWithChildren
  '/share/$token': typeof ShareTokenRoute
  '/app/sessions': typeof AppLayoutSessionsRoute
  '/app/': typeof AppLayoutIndexRoute
  '/app/sessions/$id': typeof AppLayoutSessionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/share/$token': typeof ShareTokenRoute
  '/app/sessions': typeof AppLayoutSessionsRoute
  '/app': typeof AppLayoutIndexRoute
  '/app/sessions/$id': typeof AppLayoutSessionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/_layout': typeof AppLayoutRouteWithChildren
  '/share/$token': typeof ShareTokenRoute
  '/app/_layout/sessions': typeof AppLayoutSessionsRoute
  '/app/_layout/': typeof AppLayoutIndexRoute
  '/app/_layout/sessions_/$id': typeof AppLayoutSessionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/app'
    | '/share/$token'
    | '/app/sessions'
    | '/app/'
    | '/app/sessions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/share/$token'
    | '/app/sessions'
    | '/app'
    | '/app/sessions/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/app/_layout'
    | '/share/$token'
    | '/app/_layout/sessions'
    | '/app/_layout/'
    | '/app/_layout/sessions_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  ShareTokenRoute: typeof ShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_layout': {
      id: '/app/_layout'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_layout/': {
      id: '/app/_layout/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppLayoutIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/sessions': {
      id: '/app/_layout/sessions'
      path: '/sessions'
      fullPath: '/app/sessions'
      preLoaderRoute: typeof AppLayoutSessionsRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/sessions_/$id': {
      id: '/app/_layout/sessions_/$id'
      path: '/sessions/$id'
      fullPath: '/app/sessions/$id'
      preLoaderRoute: typeof AppLayoutSessionsIdRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppLayoutSessionsRoute: typeof AppLayoutSessionsRoute
  AppLayoutIndexRoute: typeof AppLayoutIndexRoute
  AppLayoutSessionsIdRoute: typeof AppLayoutSessionsIdRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppLayoutSessionsRoute: AppLayoutSessionsRoute,
  AppLayoutIndexRoute: AppLayoutIndexRoute,
  AppLayoutSessionsIdRoute: AppLayoutSessionsIdRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AppLayoutRoute: AppLayoutRouteWithChildren,
  ShareTokenRoute: ShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
