/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppLayoutRouteImport } from './routes/app/_layout'
import { Route as AppLayoutIndexRouteImport } from './routes/app/_layout/index'
import { Route as AppLayoutSessionsRouteImport } from './routes/app/_layout/sessions'
import { Route as AppLayoutSessionsIdRouteImport } from './routes/app/_layout/sessions.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/app/_layout',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutIndexRoute = AppLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutSessionsRoute = AppLayoutSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutSessionsIdRoute = AppLayoutSessionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppLayoutSessionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app': typeof AppLayoutRouteWithChildren
  '/app/sessions': typeof AppLayoutSessionsRouteWithChildren
  '/app/': typeof AppLayoutIndexRoute
  '/app/sessions/$id': typeof AppLayoutSessionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/sessions': typeof AppLayoutSessionsRouteWithChildren
  '/app': typeof AppLayoutIndexRoute
  '/app/sessions/$id': typeof AppLayoutSessionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/_layout': typeof AppLayoutRouteWithChildren
  '/app/_layout/sessions': typeof AppLayoutSessionsRouteWithChildren
  '/app/_layout/': typeof AppLayoutIndexRoute
  '/app/_layout/sessions/$id': typeof AppLayoutSessionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/app'
    | '/app/sessions'
    | '/app/'
    | '/app/sessions/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/app/sessions' | '/app' | '/app/sessions/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/app/_layout'
    | '/app/_layout/sessions'
    | '/app/_layout/'
    | '/app/_layout/sessions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_layout': {
      id: '/app/_layout'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_layout/': {
      id: '/app/_layout/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppLayoutIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/sessions': {
      id: '/app/_layout/sessions'
      path: '/sessions'
      fullPath: '/app/sessions'
      preLoaderRoute: typeof AppLayoutSessionsRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/sessions/$id': {
      id: '/app/_layout/sessions/$id'
      path: '/$id'
      fullPath: '/app/sessions/$id'
      preLoaderRoute: typeof AppLayoutSessionsIdRouteImport
      parentRoute: typeof AppLayoutSessionsRoute
    }
  }
}

interface AppLayoutSessionsRouteChildren {
  AppLayoutSessionsIdRoute: typeof AppLayoutSessionsIdRoute
}

const AppLayoutSessionsRouteChildren: AppLayoutSessionsRouteChildren = {
  AppLayoutSessionsIdRoute: AppLayoutSessionsIdRoute,
}

const AppLayoutSessionsRouteWithChildren =
  AppLayoutSessionsRoute._addFileChildren(AppLayoutSessionsRouteChildren)

interface AppLayoutRouteChildren {
  AppLayoutSessionsRoute: typeof AppLayoutSessionsRouteWithChildren
  AppLayoutIndexRoute: typeof AppLayoutIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppLayoutSessionsRoute: AppLayoutSessionsRouteWithChildren,
  AppLayoutIndexRoute: AppLayoutIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AppLayoutRoute: AppLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
