.PHONY: writer reader worker build tidy

writer:
	go run ./cmd/writer/...

reader:
	go run ./cmd/reader/...

worker:
	go run ./cmd/worker/...

build:
	go build -o bin/writer ./cmd/writer/...
	go build -o bin/reader ./cmd/reader/...
	go build -o bin/worker ./cmd/worker/...

tidy:
	go mod tidy
